meircif/lumi-lang

- MR4/expression/container.3.mr
- MR4/expression/container.c
- MR4/expression/expression.c
- MR4/expression/initialize.c
- MR4/global/global.3.mr
- MR4/global/global.c
- MR4/mr.4.c
- MR4/mr.4.h
- MR4/syntax-tree/block.c
- MR4/syntax-tree/branch.c
- MR4/syntax-tree/function.c
- MR4/syntax-tree/node.c
- MR4/syntax-tree/root.c
- MR4/syntax-tree/test.c
- MR4/syntax-tree/type-instance.c
- MR4/syntax-tree/type.c
- MR4/syntax-tree/variable.c
- MR4/tests/expression-tests.4.mr
- MR4/tests/expression-tests.expected.c
- MR4/tests/global-tests.c
- MR4/tests/integration-expected-multiple.c
- MR4/tests/integration-expected-single.c
- MR4/tests/integration-test0.4.mr
Operators and standard input and output handling.
> Standardize various stuff in MR4 copiler

- TL4/global/global.3.lm
- TL4/global/global.c
- TL4/statement/error.3.lm
- TL4/statement/error.c
- TL4/statement/function.c
- TL4/statement/native.c
- TL4/statement/test.c
- TL4/syntax-tree/block.3.lm
- TL4/syntax-tree/block.c
- TL4/syntax-tree/code-flow.c
- TL4/syntax-tree/code.3.lm
- TL4/syntax-tree/code.c
- TL4/syntax-tree/root.c
- TL4/tests/expression-tests.4.lm
- TL4/tests/expression-tests.expected.c
- TL4/tests/syntax-tree-tests.4.lm
- TL4/tests/syntax-tree-tests.expected.c
- TL5/global/global.4.lm
- TL5/tests/ut/expression-tests.4.lm
- TL5/tests/ut/expression-tests.5.lm
- TL5/tests/ut/expression-tests.expected.c
- TL5/tests/ut/syntax-tree-tests.4.lm
- TL5/tests/ut/syntax-tree-tests.5.lm
- TL5/tests/ut/syntax-tree-tests.expected.c
- TL5/tl5-compiler.c
- lumi-command/lumi-tests.4.lm
- lumi-command/lumi.4.lm
- lumi-command/lumi.c
Allow string to grow on size incrementally
> lumi-command - make strings incremental

- TL5/global/argument.4.lm
- TL5/statement/function.4.lm
- TL5/statement/test.4.lm
- TL5/statement/type.4.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
Changes: make self in constructors be with borrow access
> TL5 - make self in constructors be with borrow access

- TL5/expression/call.4.lm
- TL5/expression/constant.4.lm
- TL5/expression/field.4.lm
- TL5/expression/initialize.4.lm
- TL5/expression/operator.4.lm
- TL5/expression/slice.4.lm
- TL5/expression/symbol.4.lm
- TL5/global/global.4.lm
- TL5/global/memory.4.lm
- TL5/global/type-instance.4.lm
- TL5/statement/function.4.lm
- TL5/statement/type.4.lm
- TL5/statement/variable.4.lm
- TL5/syntax-tree/branch.4.lm
- TL5/tests/integration/test0.5.lm
- TL5/tests/integration/test1.5.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
Changes: merge borrow access with var and add s-var access
> TL5 - merge borrow access with var and add s-var access

- TL5/expression/call.4.lm
- TL5/expression/symbol.4.lm
- TL5/global/memory.4.lm
- TL5/statement/function.4.lm
- TL5/statement/type.4.lm
- TL5/syntax-tree/branch.4.lm
- TL5/syntax-tree/root.4.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
Changes: collect type field delete on type delete
> TL5 - collect type field delete on type delete

- TL5/expression/assign.4.lm
- TL5/expression/call.4.lm
- TL5/expression/container.4.lm
- TL5/expression/expression.4.lm
- TL5/expression/initialize.4.lm
- TL5/global/global.4.lm
- TL5/global/memory.4.lm
- TL5/lumi.5.h
- TL5/statement/for.4.lm
- TL5/statement/function.4.lm
- TL5/statement/type.4.lm
- TL5/statement/variable.4.lm
- TL5/syntax-tree/block.4.lm
- TL5/syntax-tree/code-flow.4.lm
- TL5/tests/integration/test0.5.lm
- TL5/tests/integration/test1.5.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
Changes: fix various memory bugs
> TL5 - fix various memory bugs

- TL5/expression/assign.4.lm
- TL5/expression/call.4.lm
- TL5/expression/expression.4.lm
- TL5/global/memory.4.lm
- TL5/statement/for.4.lm
- TL5/statement/function.4.lm
- TL5/syntax-tree/block.4.lm
- TL5/syntax-tree/code-flow.4.lm
- TL5/syntax-tree/code.4.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
Changes: better memory management with blocks and return values
> TL5 - fix block and return value memory management

- TL5/expression/operator.4.lm
- TL5/global/global.4.lm
- TL5/lumi.5.c
- TL5/lumi.5.h
- TL5/tests/integration/error-output.txt
- TL5/tests/integration/error-test.5.lm
- TL5/tests/integration/test1.5.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
Changes: runtime zero division check
> TL5 - check zero division

- makefile
Fix makefile all and tl5-test rules
> Fix makefile all and tl5-test rules

- BUILD.bazel
- WORKSPACE
- lumi.bzl
Can be run with "bazel run //:buildifier".
> Add buildifier to autoformat bazel files

- TL5/global/global.4.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
- docs/builtin.rst
- docs/requirements.txt
Changes: ...
Added a Byte type
> Added Byte type

- .travis.yml
- TL5/expression/call.4.lm
- TL5/expression/initialize.4.lm
- TL5/global/argument.4.lm
- TL5/global/type-instance.4.lm
- TL5/statement/function.4.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/global-tests.4.lm
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
- makefile
Changes: 
- Fix #170: detect generic types inside function type arguments.
- Fix #159: fix calling native function while ignoring output
- Fix #171: illegal user error in function return assign
> Fix various bugs found in hacktoberfest

- TL5/tests/ut/expected.c
- TL5/tests/ut/from-file-test.4.lm
- TL5/tests/ut/input.5.lm
Changes: better UT input/expected file format:
- full unique names for test cases
- ignore `#` char in file end to allow testing spaces in line end
> TL5 - better UT input/expected file format

- TL4/test.sh
- TL4/tests/global-tests.3.lm
- TL4/tests/global-tests.c
Changes:
* patch TL4 UT to work with gcc9.3
* add new ignore flag to TL4 build to work with clang10
> Fix historic build problems

- .github/pull_request_template.md
- README.md
Changes:
* update PR template  with split task list
* update standard library contribution documentation
> Update PR template and standard library contribution documentation

- .codecov.yml
- .github/workflows/main.yml
- .gitignore
- .travis.yml
- README.md
- docs/functions.rst
- docs/goals.rst
- docs/install.rst
- docs/integer.rst
- docs/requirements.txt
Changes: Document Visual Studio Code syntax highlighting option.
> Document VScode syntax highlighting option

- TL5/expression/expression.4.lm
- TL5/expression/field.4.lm
- TL5/expression/initialize.4.lm
- TL5/expression/symbol.4.lm
- TL5/expression/wrap.4.lm
- TL5/global/type-instance.4.lm
- TL5/tests/ut/expected.c
- TL5/tests/ut/input.5.lm
- TL5/tl5-compiler.c
Changes: Allow passing structures with `copy` access
> Fix primitive var assign to references

- .github/workflows/main.yml
Changes: Fix broken windows CI
> Fix windows CI

- docs/conf.py
- docs/spelling_wordlist.txt
Changes: Fix repo build by:
* set explicit language in Sphinx `conf.py` as required by the recent Sphinx upgrade
* add `lm` to spelling words
> Fix sphinx config language

- docs/lumi-command.rst
- lumi-command/lumi-tests.4.lm
- lumi-command/lumi.4.lm
- lumi-command/lumi.c
Changes: In `lumi` command:
* show better error messages to the user
* add `--help`, `--verbose` and `--debug` flags
> Lumi command: show better error messages to the user
